# dictionary of every single tag (this took a while)

tagData = {

    # FUNCTION / PROCESS / CONTROL
    'function': [{"item":{"id":"bl_tag","data":{"option":"False","tag":"Is Hidden","action":"dynamic","block":"func"}},"slot":26}],
    'process': [{"item":{"id":"bl_tag","data":{"option":"False","tag":"Is Hidden","action":"dynamic","block":"process"}},"slot":26}],
    'start_process': [{"item":{"id":"bl_tag","data":{"option":"Don't copy","tag":"Local Variables","action":"dynamic","block":"start_process"}},"slot":25},{"item":{"id":"bl_tag","data":{"option":"With current targets","tag":"Target Mode","action":"dynamic","block":"start_process"}},"slot":26}],
    'Wait': [{"item":{"id":"bl_tag","data":{"option":"Ticks","tag":"Time Unit","action":"Wait","block":"control"}},"slot":26}],

    # PLAYER ACTION
    'SetEquipment': [{'item': {'id': 'bl_tag', 'data': {'option': 'Main hand', 'tag': 'Equipment Slot', 'action': 'SetEquipment', 'block': 'player_action'}}, 'slot': 26}],
    'ClearInv': [{'item': {'id': 'bl_tag', 'data': {'option': 'True', 'tag': 'Clear Crafting and Cursor', 'action': 'ClearInv', 'block': 'player_action'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'Entire inventory', 'tag': 'Clear Mode', 'action': 'ClearInv', 'block': 'player_action'}}, 'slot': 26}],
    'SendMessage': [{'item': {'id': 'bl_tag', 'data': {'option': 'Add spaces', 'tag': 'Text Value Merging', 'action': 'SendMessage', 'block': 'player_action'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'Regular', 'tag': 'Alignment Mode', 'action': 'SendMessage', 'block': 'player_action'}}, 'slot': 26}],
    'ActionBar': [{'item': {'id': 'bl_tag', 'data': {'option': 'No spaces', 'tag': 'Text Value Merging', 'action': 'ActionBar', 'block': 'player_action'}}, 'slot': 26}],
    ' SetBossBar ': [{'item': {'id': 'bl_tag', 'data': {'option': 'None', 'tag': 'Sky Effect', 'action': ' SetBossBar ', 'block': 'player_action'}}, 'slot': 24}, {'item': {'id': 'bl_tag', 'data': {'option': 'Solid', 
    'tag': 'Bar Style', 'action': ' SetBossBar ', 'block': 'player_action'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'Purple', 'tag': 'Bar Color', 'action': ' SetBossBar ', 'block': 'player_action'}}, 'slot': 26}],
    'SendAdvancement': [{'item': {'id': 'bl_tag', 'data': {'option': 'Advancement', 'tag': 'Toast Type', 'action': 'SendAdvancement', 'block': 'player_action'}}, 'slot': 26}],
    'SetTabListInfo': [{'item': {'id': 'bl_tag', 'data': {'option': 'Header', 'tag': 'Player List Field', 'action': 'SetTabListInfo', 'block': 'player_action'}}, 'slot': 26}],
    'PlaySound': [{'item': {'id': 'bl_tag', 'data': {'option': 'Master', 'tag': 'Sound Source', 'action': 'PlaySound', 'block': 'player_action'}}, 'slot': 26}],
    'StopSound': [{'item': {'id': 'bl_tag', 'data': {'option': 'Master', 'tag': 'Sound Source', 'action': 'StopSound', 'block': 'player_action'}}, 'slot': 26}],
    'AddInvRow': [{'item': {'id': 'bl_tag', 'data': {'option': 'Bottom row', 'tag': 'New Row Position', 'action': 'AddInvRow', 'block': 'player_action'}}, 'slot': 26}],
    'RemoveInvRow': [{'item': {'id': 'bl_tag', 'data': {'option': 'Bottom row', 'tag': 'Row to Remove', 'action': 'RemoveInvRow', 'block': 'player_action'}}, 'slot': 26}],
    'SetMaxHealth': [{'item': {'id': 'bl_tag', 'data': {'option': 'False', 'tag': 'Heal Player to Max Health', 'action': 'SetMaxHealth', 'block': 'player_action'}}, 'slot': 26}],
    'GiveExp': [{'item': {'id': 'bl_tag', 'data': {'option': 'Points', 'tag': 'Give Experience', 'action': 'GiveExp', 'block': 'player_action'}}, 'slot': 26}],
    'SetExp': [{'item': {'id': 'bl_tag', 'data': {'option': 'Level', 'tag': 'Set Experience', 'action': 'SetExp', 'block': 'player_action'}}, 'slot': 26}],
    'GivePotion': [{'item': {'id': 'bl_tag', 'data': {'option': 'True', 'tag': 'Show Icon', 'action': 'GivePotion', 'block': 'player_action'}}, 'slot': 24}, {'item': {'id': 'bl_tag', 'data': {'option': 'True', 'tag': 'Overwrite Effect', 'action': 'GivePotion', 'block': 'player_action'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'Regular', 'tag': 'Effect Particles', 'action': 'GivePotion', 'block': 'player_action'}}, 'slot': 26}],
    'SetAllowFlight': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Allow Flight', 'action': 'SetAllowFlight', 'block': 'player_action'}}, 'slot': 26}],
    'SetAllowPVP': [{'item': {'id': 'bl_tag', 'data': {'option': 'Disable', 'tag': 'PVP', 'action': 'SetAllowPVP', 'block': 'player_action'}}, 'slot': 26}],
    'SetDropsEnabled': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Spawn Death Drops', 'action': 'SetDropsEnabled', 'block': 'player_action'}}, 'slot': 26}],
    'SetInventoryKept': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Inventory Kept', 'action': 'SetInventoryKept', 'block': 'player_action'}}, 'slot': 26}],
    'SetCollidable': [{'item': {'id': 'bl_tag', 'data': {'option': 'Disable', 'tag': 'Collision', 'action': 'SetCollidable', 'block': 'player_action'}}, 'slot': 26}],
    'InstantRespawn': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Instant Respawn', 'action': 'InstantRespawn', 'block': 'player_action'}}, 'slot': 26}],
    'SetReducedDebug': [{'item': {'id': 'bl_tag', 'data': {'option': 'True', 'tag': 'Reduced Debug Info Enabled', 'action': 'SetReducedDebug', 'block': 'player_action'}}, 'slot': 26}],
    'Teleport': [{'item': {'id': 'bl_tag', 'data': {'option': 'False', 'tag': 'Keep Current Rotation', 'action': 'Teleport', 'block': 'player_action'}}, 'slot': 26}],
    'LaunchUp': [{'item': {'id': 'bl_tag', 'data': {'option': 'True', 'tag': 'Add to Current Velocity', 'action': 'LaunchUp', 'block': 'player_action'}}, 'slot': 26}],
    'LaunchFwd': [{'item': {'id': 'bl_tag', 'data': {'option': 'True', 'tag': 'Add to Current Velocity', 'action': 'LaunchFwd', 'block': 'player_action'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'Pitch and Yaw', 'tag': 'Launch Axis', 'action': 'LaunchFwd', 'block': 'player_action'}}, 'slot': 26}],
    'LaunchToward': [{'item': {'id': 'bl_tag', 'data': {'option': 'True', 'tag': 'Add to Current Velocity', 'action': 'LaunchToward', 'block': 'player_action'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'False', 'tag': 'Ignore Distance', 'action': 'LaunchToward', 'block': 'player_action'}}, 'slot': 26}],
    'SetFlying': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Flying', 'action': 'SetFlying', 'block': 'player_action'}}, 'slot': 26}],
    'SetGliding': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Gliding', 'action': 'SetGliding', 'block': 'player_action'}}, 'slot': 26}],
    'SetVelocity': [{'item': {'id': 'bl_tag', 'data': {'option': 'False', 'tag': 'Add to Current Velocity', 'action': 'SetVelocity', 'block': 'player_action'}}, 'slot': 26}],
    'SetPlayerWeather': [{'item': {'id': 'bl_tag', 'data': {'option': 'Downfall', 'tag': 'Weather', 'action': 'SetPlayerWeather', 'block': 'player_action'}}, 'slot': 26}],
    'DisplayFracture': [{'item': {'id': 'bl_tag', 'data': {'option': 'True', 'tag': 'Overwrite Previous Fracture', 'action': 'DisplayFracture', 'block': 'player_action'}}, 'slot': 26}],
    'DisplayBlockOpen': [{'item': {'id': 'bl_tag', 'data': {'option': 'Open', 'tag': 'Container State', 'action': 'DisplayBlockOpen', 'block': 'player_action'}}, 'slot': 26}],
    'DisplayGateway': [{'item': {'id': 'bl_tag', 'data': {'option': 'Initial beam', 'tag': 'Animation Type', 'action': 'DisplayGateway', 'block': 'player_action'}}, 'slot': 26}],
    'DisplaySignText': [{'item': {'id': 'bl_tag', 'data': {'option': 'Black', 'tag': 'Text Color', 'action': 'DisplaySignText', 'block': 'player_action'}}, 'slot': 26}],
    'SetEntityHidden': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Hidden', 'action': 'SetEntityHidden', 'block': 'player_action'}}, 'slot': 26}],
    'ParticleCuboid': [{'item': {'id': 'bl_tag', 'data': {'option': 'Wireframe', 'tag': 'Fill Type', 'action': 'ParticleCuboid', 'block': 'player_action'}}, 'slot': 26}],
    'ParticleCuboidA': [{'item': {'id': 'bl_tag', 'data': {'option': 'Wireframe', 'tag': 'Fill Type', 'action': 'ParticleCuboidA', 'block': 'player_action'}}, 'slot': 26}],
    'SetDisguiseVisible': [{'item': {'id': 'bl_tag', 'data': {'option': 'Disable', 'tag': 'Disguise Visible', 'action': 'SetDisguiseVisible', 'block': 'player_action'}}, 'slot': 26}],
    'AttackAnimation': [{'item': {'id': 'bl_tag', 'data': {'option': 'Swing main arm', 'tag': 'Animation Arm', 'action': 'AttackAnimation', 'block': 'player_action'}}, 'slot': 26}],
    'SendAnimation': [{'item': {'id': 'bl_tag', 'data': {'option': 'Hurt animation', 'tag': 'Animation Type', 'action': 'SendAnimation', 'block': 'player_action'}}, 'slot': 26}],

    # IF PLAYER
    'IsLookingAt': [{'item': {'id': 'bl_tag', 'data': {'option': 'Ignore fluids', 'tag': 'Fluid Mode', 'action': 'IsLookingAt', 'block': 'if_player'}}, 'slot': 26}],
    'IsNear': [{'item': {'id': 'bl_tag', 'data': {'option': 'Sphere', 'tag': 'Shape', 'action': 'PIsNear', 'block': 'if_player'}}, 'slot': 26}],
    'IsHolding': [{'item': {'id': 'bl_tag', 'data': {'option': 'Either hand', 'tag': 'Hand Slot', 'action': 'IsHolding', 'block': 'if_player'}}, 'slot': 26}],
    'HasItem': [{'item': {'id': 'bl_tag', 'data': {'option': 'Has Any Item', 'tag': 'Check Mode', 'action': 'HasItem', 'block': 'if_player'}}, 'slot': 26}],
    'IsWearing': [{'item': {'id': 'bl_tag', 'data': {'option': 'Is Wearing Some', 'tag': 'Check Mode', 'action': 'PIsWearing', 'block': 'if_player'}}, 'slot': 26}],
    'HasRoomForItem': [{'item': {'id': 'bl_tag', 'data': {'option': 'Main inventory', 'tag': 'Checked Slots', 'action': 'HasRoomForItem', 'block': 'if_player'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'Has Room for Any Item', 'tag': 'Check Mode', 'action': 'HasRoomForItem', 'block': 'if_player'}}, 'slot': 26}],

    # GAME ACTION
    'SpawnItem': [{'item': {'id': 'bl_tag', 'data': {'option': 'True', 'tag': 'Apply Item Motion', 'action': 'SpawnItem', 'block': 'game_action'}}, 'slot': 26}],
    'Firework': [{'item': {'id': 'bl_tag', 'data': {'option': 'False', 'tag': 'Instant', 'action': 'Firework', 'block': 'game_action'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'Upwards', 'tag': 'Movement', 'action': 'Firework', 'block': 'game_action'}}, 'slot': 26}],
    'FallingBlock': [{'item': {'id': 'bl_tag', 'data': {'option': 'True', 'tag': 'Reform on Impact', 'action': 'FallingBlock', 'block': 'game_action'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'False', 'tag': 'Hurt Hit Entities', 'action': 'FallingBlock', 'block': 'game_action'}}, 'slot': 26}],
    'SpawnArmorStand': [{'item': {'id': 'bl_tag', 'data': {'option': 'Visible', 'tag': 'Visibility', 'action': 'SpawnArmorStand', 'block': 'game_action'}}, 'slot': 26}],
    'SpawnCrystal': [{'item': {'id': 'bl_tag', 'data': {'option': 'True', 'tag': 'Show Bottom', 'action': 'SpawnCrystal', 'block': 'game_action'}}, 'slot': 26}],
    'SpawnEnderEye': [{'item': {'id': 'bl_tag', 'data': {'option': 'Random', 'tag': 'End of Lifespan', 'action': 'SpawnEnderEye', 'block': 'game_action'}}, 'slot': 26}],
    'CloneRegion': [{'item': {'id': 'bl_tag', 'data': {'option': 'False', 'tag': 'Ignore Air', 'action': 'CloneRegion', 'block': 'game_action'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'True', 'tag': 'Clone Block Entities', 'action': 'CloneRegion', 'block': 'game_action'}}, 'slot': 26}],
    'BoneMeal': [{'item': {'id': 'bl_tag', 'data': {'option': 'True', 'tag': 'Show Particles', 'action': 'BoneMeal', 'block': 'game_action'}}, 'slot': 26}],
    'GenerateTree': [{'item': {'id': 'bl_tag', 'data': {'option': 'Oak Tree', 'tag': 'Tree Type', 'action': 'GenerateTree', 'block': 'game_action'}}, 'slot': 26}],
    'SetBlockGrowth': [{'item': {'id': 'bl_tag', 'data': {'option': 'Growth Stage Number', 'tag': 'Growth Unit', 'action': 'SetBlockGrowth', 'block': 'game_action'}}, 'slot': 26}],
    'SetCampfireItem': [{'item': {'id': 'bl_tag', 'data': {'option': '1', 'tag': 'Campfire Slot', 'action': 'SetCampfireItem', 'block': 'game_action'}}, 'slot': 26}],
    'WebRequest': [{'item': {'id': 'bl_tag', 'data': {'option': 'Post', 'tag': 'Request Method', 'action': 'WebRequest', 'block': 'game_action'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'text/plain', 'tag': 'Content Type', 'action': 'WebRequest', 'block': 'game_action'}}, 'slot': 26}],

    # IF GAME
    'BlockPowered': [{'item': {'id': 'bl_tag', 'data': {'option': 'Direct power', 'tag': 'Redstone Power Mode', 'action': 'BlockPowered', 'block': 'if_game'}}, 'slot': 26}],
    'HasRoomForItem': [{'item': {'id': 'bl_tag', 'data': {'option': 'Has Room for Any Item', 'tag': 'Check Mode', 'action': 'HasRoomForItem', 'block': 'if_game'}}, 'slot': 26}],
    'SignHasTxt': [{'item': {'id': 'bl_tag', 'data': {'option': 'Contains', 'tag': 'Check Mode', 'action': 'SignHasTxt', 'block': 'if_game'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'All lines', 'tag': 'Sign Line', 'action': 'SignHasTxt', 'block': 'if_game'}}, 'slot': 26}],
    'EventItemEquals': [{'item': {'id': 'bl_tag', 'data': {'option': 'Ignore stack size/durability', 'tag': 'Comparison Mode', 'action': 'EventItemEquals', 'block': 'if_game'}}, 'slot': 26}],
    'CommandEquals': [{'item': {'id': 'bl_tag', 'data': {'option': 'True', 'tag': 'Ignore Case', 'action': 'CommandEquals', 'block': 'if_game'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'Check entire command', 'tag': 'Check Mode', 'action': 'CommandEquals', 'block': 'if_game'}}, 'slot': 26}],
    'CmdArgEquals': [{'item': {'id': 'bl_tag', 'data': {'option': 'True', 'tag': 'Ignore Case', 'action': 'CmdArgEquals', 'block': 'if_game'}}, 'slot': 26}],

    # ENTITY ACTION
    'SetMaxHealth': [{'item': {'id': 'bl_tag', 'data': {'option': 'False', 'tag': 'Heal Mob to Max Health', 'action': 'SetMaxHealth', 'block': 'entity_action'}}, 'slot': 26}],
    'GivePotion': [{'item': {'id': 'bl_tag', 'data': {'option': 'True', 'tag': 'Overwrite Effect', 'action': 'GivePotion', 'block': 'entity_action'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'Regular', 'tag': 'Effect Particles', 'action': 'GivePotion', 'block': 'entity_action'}}, 'slot': 26}],
    'SetAge': [{'item': {'id': 'bl_tag', 'data': {'option': "Don't change", 'tag': 'Age Lock', 'action': 'SetAge', 'block': 'entity_action'}}, 'slot': 26}],
    'Teleport': [{'item': {'id': 'bl_tag', 'data': {'option': 'False', 'tag': 'Keep Current Rotation', 'action': 'Teleport', 'block': 'entity_action'}}, 'slot': 26}],
    'LaunchUp': [{'item': {'id': 'bl_tag', 'data': {'option': 'True', 'tag': 'Add to Current Velocity', 'action': 'LaunchUp', 'block': 'entity_action'}}, 'slot': 26}],
    'LaunchFwd': [{'item': {'id': 'bl_tag', 'data': {'option': 'True', 'tag': 'Add to Current Velocity', 'action': 'LaunchFwd', 'block': 'entity_action'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'Pitch and Yaw', 'tag': 'Launch Axis', 'action': 'LaunchFwd', 'block': 'entity_action'}}, 'slot': 26}],
    'LaunchToward': [{'item': {'id': 'bl_tag', 'data': {'option': 'True', 'tag': 'Add to Current Velocity', 'action': 'LaunchToward', 'block': 'entity_action'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'False', 'tag': 'Ignore Distance', 'action': 'LaunchToward', 'block': 'entity_action'}}, 'slot': 26}],
    'SetGliding': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Gliding', 'action': 'SetGliding', 'block': 'entity_action'}}, 'slot': 26}],
    'SetGravity': [{'item': {'id': 'bl_tag', 'data': {'option': 'Disable', 'tag': 'Gravity', 'action': 'SetGravity', 'block': 'entity_action'}}, 'slot': 26}],
    'SetVelocity': [{'item': {'id': 'bl_tag', 'data': {'option': 'False', 'tag': 'Add to Current Velocity', 'action': 'SetVelocity', 'block': 'entity_action'}}, 'slot': 26}],
    'SetName': [{'item': {'id': 'bl_tag', 'data': {'option': 'False', 'tag': 'Hide Name Tag', 'action': 'SetName', 'block': 'entity_action'}}, 'slot': 26}],
    'SetNameVisible': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Name Tag Visible', 'action': 'SetNameVisible', 'block': 'entity_action'}}, 'slot': 26}],
    'SetAI': [{'item': {'id': 'bl_tag', 'data': {'option': 'None', 'tag': 'AI', 'action': 'SetAI', 'block': 'entity_action'}}, 'slot': 26}],
    'SetSilenced': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Silenced', 'action': 'SetSilenced', 'block': 'entity_action'}}, 'slot': 26}],
    'SetDeathDrops': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Has Death Drops', 'action': 'SetDeathDrops', 'block': 'entity_action'}}, 'slot': 26}],
    'SetCollidable': [{'item': {'id': 'bl_tag', 'data': {'option': 'Disable', 'tag': 'Collision', 'action': 'SetCollidable', 'block': 'entity_action'}}, 'slot': 26}],
    'SetInvulnerable': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Invulnerable', 'action': 'SetInvulnerable', 'block': 'entity_action'}}, 'slot': 26}],
    'SetMobSitting': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Is Sitting', 'action': 'SetMobSitting', 'block': 'entity_action'}}, 'slot': 26}],
    'SetBaby': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Baby', 'action': 'SetBaby', 'block': 'entity_action'}}, 'slot': 26}],
    'SetSheepSheared': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Sheared', 'action': 'SetSheepSheared', 'block': 'entity_action'}}, 'slot': 26}],
    'SetSaddle': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Saddle', 'action': 'SetSaddle', 'block': 'entity_action'}}, 'slot': 26}],
    'SetCarryingChest': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Carrying Chest', 'action': 'SetCarryingChest', 'block': 'entity_action'}}, 'slot': 26}],
    'ArmorStandSlots': [{'item': {'id': 'bl_tag', 'data': {'option': 'Take, swap or place item', 'tag': 'Interactions', 'action': 'ArmorStandSlots', 'block': 'entity_action'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 
    'data': {'option': 'All', 'tag': 'Equipment Slot', 'action': 'ArmorStandSlots', 'block': 'entity_action'}}, 'slot': 26}],
    'SetMarker': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Marker', 'action': 'SetMarker', 'block': 'entity_action'}}, 'slot': 26}],
    'SetAngry': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Angry', 'action': 'SetAngry', 'block': 'entity_action'}}, 'slot': 26}],
    'SetRearing': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Rearing', 'action': 'SetRearing', 'block': 'entity_action'}}, 'slot': 26}],
    'SetRiptiding': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Riptiding', 'action': 'SetRiptiding', 'block': 'entity_action'}}, 'slot': 26}],
    'CreeperCharged': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Charged', 'action': 'CreeperCharged', 'block': 'entity_action'}}, 'slot': 26}],
    'SetInvisible': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Invisible', 'action': 'SetInvisible', 'block': 'entity_action'}}, 'slot': 26}],
    'SetPandaGene': [{'item': {'id': 'bl_tag', 'data': {'option': 'Both', 'tag': 'Set Gene', 'action': 'SetPandaGene', 'block': 'entity_action'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'Aggressive', 'tag': 'Gene Type', 'action': 'SetPandaGene', 'block': 'entity_action'}}, 'slot': 26}],
    'SetProfession': [{'item': {'id': 'bl_tag', 'data': {'option': 'Armorer', 'tag': 'Profession', 'action': 'SetProfession', 'block': 'entity_action'}}, 'slot': 26}],
    'SetPersistent': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Persistent', 'action': 'SetPersistent', 'block': 'entity_action'}}, 'slot': 26}],
    'SetGlowing': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Glowing', 'action': 'SetGlowing', 'block': 'entity_action'}}, 'slot': 26}],
    'SetDyeColor': [{'item': {'id': 'bl_tag', 'data': {'option': 'White', 'tag': 'Dye', 'action': 'SetDyeColor', 'block': 'entity_action'}}, 'slot': 26}],
    'SetFishPattern': [{'item': {'id': 'bl_tag', 'data': {'option': 'White', 'tag': 'Pattern Color', 'action': 'SetFishPattern', 'block': 'entity_action'}}, 'slot': 24}, {'item': {'id': 'bl_tag', 'data': {'option': 'White', 'tag': 'Body Color', 'action': 'SetFishPattern', 'block': 'entity_action'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'Kob', 'tag': 'Pattern', 'action': 'SetFishPattern', 'block': 'entity_action'}}, 'slot': 26}],
    'SetRabbitType': [{'item': {'id': 'bl_tag', 'data': {'option': 'Brown', 'tag': 'Skin Type', 'action': 'SetRabbitType', 'block': 'entity_action'}}, 'slot': 26}],
    'SetCatType': [{'item': {'id': 'bl_tag', 'data': {'option': 'Tabby', 'tag': 'Skin Type', 'action': 'SetCatType', 'block': 'entity_action'}}, 'slot': 26}],
    'MooshroomType': [{'item': {'id': 'bl_tag', 'data': {'option': 'Red', 'tag': 'Mooshroom Variant', 'action': 'MooshroomType', 'block': 'entity_action'}}, 'slot': 26}],
    'SetFoxType': [{'item': {'id': 'bl_tag', 'data': {'option': 'Red', 'tag': 'Fox Type', 'action': 'SetFoxType', 'block': 'entity_action'}}, 'slot': 26}],
    'SetParrotColor': [{'item': {'id': 'bl_tag', 'data': {'option': 'Red', 'tag': 'Parrot Color', 'action': 'SetParrotColor', 'block': 'entity_action'}}, 'slot': 26}],
    'SetHorsePattern': [{'item': {'id': 'bl_tag', 'data': {'option': 'Flaxen chestnut', 'tag': 'Horse Color', 'action': 'SetHorsePattern', 'block': 'entity_action'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'Stockings and blaze', 'tag': 'Horse Markings', 'action': 'SetHorsePattern', 'block': 'entity_action'}}, 'slot': 26}],
    'SetLlamaColor': [{'item': {'id': 'bl_tag', 'data': {'option': 'Brown', 'tag': 'Llama Color', 'action': 'SetLlamaColor', 'block': 'entity_action'}}, 'slot': 26}],
    'SetVillagerBiome': [{'item': {'id': 'bl_tag', 'data': {'option': 'Desert', 'tag': 'Biome', 'action': 'SetVillagerBiome', 'block': 'entity_action'}}, 'slot': 26}],
    'SnowmanPumpkin': [{'item': {'id': 'bl_tag', 'data': {'option': 'Disable', 'tag': 'Pumpkin', 'action': 'SnowmanPumpkin', 'block': 'entity_action'}}, 'slot': 26}],
    'ArmorStandParts': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Arms', 'action': 'ArmorStandParts', 'block': 'entity_action'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Base Plate', 'action': 'ArmorStandParts', 'block': 'entity_action'}}, 'slot': 26}],
    'SetBeeNectar': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Has Nectar', 'action': 'SetBeeNectar', 'block': 'entity_action'}}, 'slot': 26}],
    'SendAnimation': [{'item': {'id': 'bl_tag', 'data': {'option': 'Hurt animation', 'tag': 'Animation Type', 'action': 'SendAnimation', 'block': 'entity_action'}}, 'slot': 26}],
    'AttackAnimation': [{'item': {'id': 'bl_tag', 'data': {'option': 'Swing main arm', 'tag': 'Animation Arm', 'action': 'AttackAnimation', 'block': 'entity_action'}}, 'slot': 26}],
    'ArmorStandPose': [{'item': {'id': 'bl_tag', 'data': {'option': 'Head', 'tag': 'Armor Stand Part', 'action': 'ArmorStandPose', 'block': 'entity_action'}}, 'slot': 26}],
    ' SetPose ': [{'item': {'id': 'bl_tag', 'data': {'option': 'Standing', 'tag': 'Pose', 'action': ' SetPose ', 'block': 'entity_action'}}, 'slot': 26}],
    'SetFoxLeaping': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Leaping', 'action': 'SetFoxLeaping', 'block': 'entity_action'}}, 'slot': 26}],
    'SetArmsRaised': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Arms Raised', 'action': 'SetArmsRaised', 'block': 'entity_action'}}, 'slot': 26}],
    'SetCatResting': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Resting', 'action': 'SetCatResting', 'block': 'entity_action'}}, 'slot': 26}],
    'SetCelebrating': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Celebrate', 'action': 'SetCelebrating', 'block': 'entity_action'}}, 'slot': 26}],
    'FoxSleeping': [{'item': {'id': 'bl_tag', 'data': {'option': 'Enable', 'tag': 'Sleeping', 'action': 'FoxSleeping', 'block': 'entity_action'}}, 'slot': 26}],
    'SetDragonPhase': [{'item': {'id': 'bl_tag', 'data': {'option': 'Flying', 'tag': 'Phase', 'action': 'SetDragonPhase', 'block': 'entity_action'}}, 'slot': 26}],
    'SetEquipment': [{'item': {'id': 'bl_tag', 'data': {'option': 'Main hand', 'tag': 'Equipment Slot', 'action': 'SetEquipment', 'block': 'entity_action'}}, 'slot': 26}],

    # IF ENTITY
    'IsNear': [{'item': {'id': 'bl_tag', 'data': {'option': 'Sphere', 'tag': 'Shape', 'action': 'EIsNear', 'block': 'if_entity'}}, 'slot': 26}],
    'IsRiding': [{'item': {'id': 'bl_tag', 'data': {'option': 'Entity type', 'tag': 'Compare Text To', 'action': 'IsRiding', 'block': 'if_entity'}}, 'slot': 26}],
    'HasPotion': [{'item': {'id': 'bl_tag', 'data': {'option': 'None', 'tag': 'Check Properties', 'action': 'HasPotion', 'block': 'if_entity'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'Has any effect', 'tag': 'Check Mode', 'action': 'HasPotion', 'block': 'if_entity'}}, 'slot': 26}],

    # SET VAR
    'PurgeVars': [{'item': {'id': 'bl_tag', 'data': {'option': 'Full word(s) in name', 'tag': 'Match Requirement', 'action': 'PurgeVars', 'block': 'set_var'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'False', 'tag': 'Ignore Case', 'action': 'PurgeVars', 'block': 'set_var'}}, 'slot': 26}],
    '/': [{'item': {'id': 'bl_tag', 'data': {'option': 'Default', 'tag': 'Division Mode', 'action': '/', 'block': 'set_var'}}, 'slot': 26}],
    'RandomNumber': [{'item': {'id': 'bl_tag', 'data': {'option': 'Whole number', 'tag': 'Rounding Mode', 'action': 'RandomNumber', 'block': 'set_var'}}, 'slot': 26}],
    'Round': [{'item': {'id': 'bl_tag', 'data': {'option': 'Nearest', 'tag': 'Round Mode', 'action': 'Round', 'block': 'set_var'}}, 'slot': 26}],
    'NormalRandom': [{'item': {'id': 'bl_tag', 'data': {'option': 'Normal', 'tag': 'Distribution', 'action': 'NormalRandom', 'block': 'set_var'}}, 'slot': 26}],
    'Sine': [{'item': {'id': 'bl_tag', 'data': {'option': 'Sine', 'tag': 'Sine Variant', 'action': 'Sine', 'block': 'set_var'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'Degrees', 'tag': 'Input', 'action': 'Sine', 'block': 'set_var'}}, 'slot': 26}],
    'Cosine': [{'item': {'id': 'bl_tag', 'data': {'option': 'Cosine', 'tag': 'Cosine Variant', 'action': 'Cosine', 'block': 'set_var'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'Degrees', 'tag': 'Input', 'action': 'Cosine', 'block': 'set_var'}}, 'slot': 26}],
    'Tangent': [{'item': {'id': 'bl_tag', 'data': {'option': 'Tangent', 'tag': 'Tangent Variant', 'action': 'Tangent', 'block': 'set_var'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'Degrees', 'tag': 'Input', 'action': 'Tangent', 'block': 'set_var'}}, 'slot': 26}],
    'PerlinNoise': [{'item': {'id': 'bl_tag', 'data': {'option': 'Brownian', 'tag': 'Fractal Type', 'action': 'PerlinNoise', 'block': 'set_var'}}, 'slot': 26}],
    'VoronoiNoise': [{'item': {'id': 'bl_tag', 'data': {'option': 'Euclidean', 'tag': 'Cell Edge Type', 'action': 'VoronoiNoise', 'block': 'set_var'}}, 'slot': 26}],
    'WorleyNoise': [{'item': {'id': 'bl_tag', 'data': {'option': 'Euclidean', 'tag': 'Cell Edge Type', 'action': 'WorleyNoise', 'block': 'set_var'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'Primary', 'tag': 'Distance Calculation', 'action': 'WorleyNoise', 'block': 'set_var'}}, 'slot': 26}],
    'Bitwise': [{'item': {'id': 'bl_tag', 'data': {'option': '|', 'tag': 'Operator', 'action': 'Bitwise', 'block': 'set_var'}}, 'slot': 26}],
    'Text': [{'item': {'id': 'bl_tag', 'data': {'option': 'No spaces', 'tag': 'Text Value Merging', 'action': 'Text', 'block': 'set_var'}}, 'slot': 26}],
    'ReplaceText': [{'item': {'id': 'bl_tag', 'data': {'option': 'All occurrences', 'tag': 'Replacement Type', 'action': 'ReplaceText', 'block': 'set_var'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 
    'Disable', 'tag': 'Regular Expressions', 'action': 'ReplaceText', 'block': 'set_var'}}, 'slot': 26}],
    'RemoveText': [{'item': {'id': 'bl_tag', 'data': {'option': 'Disable', 'tag': 'Regular Expressions', 'action': 'RemoveText', 'block': 'set_var'}}, 'slot': 26}],
    'SetCase': [{'item': {'id': 'bl_tag', 'data': {'option': 'UPPERCASE', 'tag': 'Capitalization Type', 'action': 'SetCase', 'block': 'set_var'}}, 'slot': 26}],
    'TranslateColors': [{'item': {'id': 'bl_tag', 'data': {'option': 'From & to color', 'tag': 'Translation Type', 'action': 'TranslateColors', 'block': 'set_var'}}, 'slot': 26}],
    'FormatTime': [{'item': {'id': 'bl_tag', 'data': {'option': '2020/08/17 17:20:54', 'tag': 'Format', 'action': 'FormatTime', 'block': 'set_var'}}, 'slot': 26}],
    'GetCoord': [{'item': {'id': 'bl_tag', 'data': {'option': 'Plot coordinate', 'tag': 'Coordinate Type', 'action': 'GetCoord', 'block': 'set_var'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'X', 'tag': 'Coordinate', 'action': 'GetCoord', 'block': 'set_var'}}, 'slot': 26}],
    'SetCoord': [{'item': {'id': 'bl_tag', 'data': {'option': 'Plot coordinate', 'tag': 'Coordinate Type', 'action': 'SetCoord', 'block': 'set_var'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'X', 'tag': 'Coordinate', 'action': 'SetCoord', 'block': 'set_var'}}, 'slot': 26}],
    'SetAllCoords': [{'item': {'id': 'bl_tag', 'data': {'option': 'Plot coordinate', 'tag': 'Coordinate Type', 'action': 'SetAllCoords', 'block': 'set_var'}}, 'slot': 26}],
    'ShiftOnAxis': [{'item': {'id': 'bl_tag', 'data': {'option': 'X', 'tag': 'Coordinate', 'action': 'ShiftOnAxis', 'block': 'set_var'}}, 'slot': 26}],
    'ShiftInDirection': [{'item': {'id': 'bl_tag', 'data': {'option': 'Forward', 'tag': 'Direction', 'action': 'ShiftInDirection', 'block': 'set_var'}}, 'slot': 26}],
    'ShiftOnVector': [{'item': {'id': 'bl_tag', 'data': {'option': 'False', 'tag': 'Add Location Rotation', 'action': 'ShiftOnVector', 'block': 'set_var'}}, 'slot': 26}],
    'ShiftRotation': [{'item': {'id': 'bl_tag', 'data': {'option': 'Pitch', 'tag': 'Rotation Axis', 'action': 'ShiftRotation', 'block': 'set_var'}}, 'slot': 26}],
    'FaceLocation': [{'item': {'id': 'bl_tag', 'data': {'option': 'Toward location', 'tag': 'Face Direction', 'action': 'FaceLocation', 'block': 'set_var'}}, 'slot': 26}],
    'AlignLoc': [{'item': {'id': 'bl_tag', 'data': {'option': 'Keep rotation', 'tag': 'Rotation', 'action': 'AlignLoc', 'block': 'set_var'}}, 'slot': 24}, {'item': {'id': 'bl_tag', 'data': {'option': 'All coordinates', 'tag': 'Coordinates', 'action': 'AlignLoc', 'block': 'set_var'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'Block center', 'tag': 'Alignment Mode', 'action': 'AlignLoc', 'block': 'set_var'}}, 
    'slot': 26}],
    'Distance': [{'item': {'id': 'bl_tag', 'data': {'option': 'Distance 3D (X/Y/Z)', 'tag': 'Distance Type', 'action': 'Distance', 'block': 'set_var'}}, 'slot': 26}],
    'GetItemType': [{'item': {'id': 'bl_tag', 'data': {'option': 'Item ID (golden_apple)', 'tag': 'Return Value Type', 'action': 'GetItemType', 'block': 'set_var'}}, 'slot': 26}],
    'GetItemDura': [{'item': {'id': 'bl_tag', 'data': {'option': 'Get Damage', 'tag': 'Durability Type', 'action': 'GetItemDura', 'block': 'set_var'}}, 'slot': 26}],
    'SetItemDura': [{'item': {'id': 'bl_tag', 'data': {'option': 'Set Damage', 'tag': 'Durability Type', 'action': 'SetItemDura', 'block': 'set_var'}}, 'slot': 26}],
    'SetBreakability': [{'item': {'id': 'bl_tag', 'data': {'option': 'Unbreakable', 'tag': 'Breakability', 'action': 'SetBreakability', 'block': 'set_var'}}, 'slot': 26}],
    'GetHeadOwner': [{'item': {'id': 'bl_tag', 'data': {'option': 'Owner Name', 'tag': 'Text Value', 'action': 'GetHeadOwner', 'block': 'set_var'}}, 'slot': 26}],
    'SetItemFlags': [{'item': {'id': 'bl_tag', 'data': {'option': 'No Change', 'tag': 'Hide Color', 'action': 'SetItemFlags', 'block': 'set_var'}}, 'slot': 20}, {'item': {'id': 'bl_tag', 'data': {'option': 'No Change', 'tag': 'Hide Enchantments', 'action': 'SetItemFlags', 'block': 'set_var'}}, 'slot': 21}, {'item': {'id': 'bl_tag', 'data': {'option': 'No Change', 'tag': 'Hide Attributes', 'action': 'SetItemFlags', 'block': 'set_var'}}, 'slot': 22}, {'item': {'id': 'bl_tag', 'data': {'option': 'No Change', 'tag': 'Hide Unbreakable', 'action': 'SetItemFlags', 'block': 'set_var'}}, 'slot': 23}, {'item': {'id': 'bl_tag', 'data': {'option': 'No Change', 'tag': 'Hide Can Destroy', 'action': 'SetItemFlags', 'block': 'set_var'}}, 'slot': 24}, {'item': {'id': 'bl_tag', 'data': {'option': 'No Change', 'tag': 'Hide Can Place On', 'action': 'SetItemFlags', 'block': 'set_var'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'No Change', 'tag': 'Hide Potion Effects', 'action': 'SetItemFlags', 'block': 'set_var'}}, 'slot': 26}],
    'SetLodestoneLoc': [{'item': {'id': 'bl_tag', 'data': {'option': 'False', 'tag': 'Require Lodestone at Location', 'action': 'SetLodestoneLoc', 'block': 'set_var'}}, 'slot': 26}],
    'GetItemAttribute': [{'item': {'id': 'bl_tag', 'data': {'option': 'Armor', 'tag': 'Attribute', 'action': 'GetItemAttribute', 'block': 'set_var'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'Any', 
    'tag': 'Active Equipment Slot', 'action': 'GetItemAttribute', 'block': 'set_var'}}, 'slot': 26}],
    'AddItemAttribute': [{'item': {'id': 'bl_tag', 'data': {'option': 'Armor', 'tag': 'Attribute', 'action': 'AddItemAttribute', 'block': 'set_var'}}, 'slot': 24}, {'item': {'id': 'bl_tag', 'data': {'option': 'Add number', 'tag': 'Operation', 'action': 'AddItemAttribute', 'block': 'set_var'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'Main hand', 'tag': 'Active Equipment Slot', 'action': 'AddItemAttribute', 
    'block': 'set_var'}}, 'slot': 26}],
    'GetValueIndex': [{'item': {'id': 'bl_tag', 'data': {'option': 'Ascending (first index)', 'tag': 'Search Order', 'action': 'GetValueIndex', 'block': 'set_var'}}, 'slot': 26}],
    'SortList': [{'item': {'id': 'bl_tag', 'data': {'option': 'Ascending', 'tag': 'Sort Order', 'action': 'SortList', 'block': 'set_var'}}, 'slot': 26}],
    'GetParticleSprd': [{'item': {'id': 'bl_tag', 'data': {'option': 'Horizontal', 'tag': 'Spread', 'action': 'GetParticleSprd', 'block': 'set_var'}}, 'slot': 26}],
    'GetBlockType': [{'item': {'id': 'bl_tag', 'data': {'option': 'Block ID (oak_log)', 'tag': 'Return Value Type', 'action': 'GetBlockType', 'block': 'set_var'}}, 'slot': 26}],
    'GetAllBlockData': [{'item': {'id': 'bl_tag', 'data': {'option': 'True', 'tag': 'Hide Default', 'action': 'GetAllBlockData', 'block': 'set_var'}}, 'slot': 26}],
    'GetBlockGrowth': [{'item': {'id': 'bl_tag', 'data': {'option': 'Growth stage number', 'tag': 'Growth Unit', 'action': 'GetBlockGrowth', 'block': 'set_var'}}, 'slot': 26}],
    'GetLight': [{'item': {'id': 'bl_tag', 'data': {'option': 'Combined light', 'tag': 'Light Type', 'action': 'GetLight', 'block': 'set_var'}}, 'slot': 26}],
    'GetSignText': [{'item': {'id': 'bl_tag', 'data': {'option': '1', 'tag': 'Sign Line', 'action': 'GetSignText', 'block': 'set_var'}}, 'slot': 26}],
    'GetContainerItems': [{'item': {'id': 'bl_tag', 'data': {'option': 'False', 'tag': 'Ignore Empty Slots', 'action': 'GetContainerItems', 'block': 'set_var'}}, 'slot': 26}],
    'Raycast': [{'item': {'id': 'bl_tag', 'data': {'option': 'False', 'tag': 'Entity Collision', 'action': 'Raycast', 'block': 'set_var'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'All blocks', 'tag': 'Block Collision', 'action': 'Raycast', 'block': 'set_var'}}, 'slot': 26}],
    'GetSoundPitch': [{'item': {'id': 'bl_tag', 'data': {'option': 'Pitch (number)', 'tag': 'Return Value Type', 'action': 'GetSoundPitch', 'block': 'set_var'}}, 'slot': 26}],
    'GetColorChannels': [{'item': {'id': 'bl_tag', 'data': {'option': 'RGB', 'tag': 'Color Channels', 'action': 'GetColorChannels', 'block': 'set_var'}}, 'slot': 26}],
    'GetVectorComp': [{'item': {'id': 'bl_tag', 'data': {'option': 'X', 'tag': 'Component', 'action': 'GetVectorComp', 'block': 'set_var'}}, 'slot': 26}],
    'SetVectorComp': [{'item': {'id': 'bl_tag', 'data': {'option': 'X', 'tag': 'Component', 'action': 'SetVectorComp', 'block': 'set_var'}}, 'slot': 26}],
    'GetVectorLength': [{'item': {'id': 'bl_tag', 'data': {'option': 'Length', 'tag': 'Length Type', 'action': 'GetVectorLength', 'block': 'set_var'}}, 'slot': 26}],
    'RotateAroundAxis': [{'item': {'id': 'bl_tag', 'data': {'option': 'X', 'tag': 'Axis', 'action': 'RotateAroundAxis', 'block': 'set_var'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'Degrees', 'tag': 'Angle Units', 'action': 'RotateAroundAxis', 'block': 'set_var'}}, 'slot': 26}],
    'RotateAroundVec': [{'item': {'id': 'bl_tag', 'data': {'option': 'Degrees', 'tag': 'Angle Units', 'action': 'RotateAroundVec', 'block': 'set_var'}}, 'slot': 26}],

    # IF VAR
    'LocIsNear': [{'item': {'id': 'bl_tag', 'data': {'option': 'Sphere', 'tag': 'Shape', 'action': 'LocIsNear', 'block': 'if_var'}}, 'slot': 26}],
    ' TextMatches ': [{'item': {'id': 'bl_tag', 'data': {'option': 'False', 'tag': 'Ignore Case', 'action': ' TextMatches ', 'block': 'if_var'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'Disable', 'tag': 'Regular Expressions', 'action': ' TextMatches ', 'block': 'if_var'}}, 'slot': 26}],
    'Contains': [{'item': {'id': 'bl_tag', 'data': {'option': 'False', 'tag': 'Ignore Case', 'action': 'Contains', 'block': 'if_var'}}, 'slot': 26}],
    'StartsWith': [{'item': {'id': 'bl_tag', 'data': {'option': 'False', 'tag': 'Ignore Case', 'action': 'StartsWith', 'block': 'if_var'}}, 'slot': 26}],
    'EndsWith': [{'item': {'id': 'bl_tag', 'data': {'option': 'False', 'tag': 'Ignore Case', 'action': 'EndsWith', 'block': 'if_var'}}, 'slot': 26}],
    'VarIsType': [{'item': {'id': 'bl_tag', 'data': {'option': 'Number', 'tag': 'Variable Type', 'action': 'VarIsType', 'block': 'if_var'}}, 'slot': 26}],
    'ItemEquals': [{'item': {'id': 'bl_tag', 'data': {'option': 'Exactly equals', 'tag': 'Comparison Mode', 'action': 'VItemEquals', 'block': 'if_var'}}, 'slot': 26}],

    # SELECT OBJECT
    'EventTarget': [{'item': {'id': 'bl_tag', 'data': {'option': 'Default', 'tag': 'Event Target', 'action': 'EventTarget', 'block': 'select_obj'}}, 'slot': 26}],
    'FilterDistance': [{'item': {'id': 'bl_tag', 'data': {'option': 'False', 'tag': 'Ignore Y-Axis', 'action': 'FilterDistance', 'block': 'select_obj'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'Nearest', 'tag': 'Compare Mode', 'action': 'FilterDistance', 'block': 'select_obj'}}, 'slot': 26}],
    'FilterSort': [{'item': {'id': 'bl_tag', 'data': {'option': 'Ascending', 'tag': 'Sort Order', 'action': 'FilterSort', 'block': 'select_obj'}}, 'slot': 26}],
    'FilterRay': [{'item': {'id': 'bl_tag', 'data': {'option': 'Solid blocks', 'tag': 'Block Collision', 'action': 'FilterRay', 'block': 'select_obj'}}, 'slot': 26}],

    # REPEAT
    'ForEach': [{'item': {'id': 'bl_tag', 'data': {'option': 'True', 'tag': 'Allow List Changes', 'action': 'ForEach', 'block': 'repeat'}}, 'slot': 26}],
    'Adjacent': [{'item': {'id': 'bl_tag', 'data': {'option': 'False', 'tag': 'Change Location Rotation', 'action': 'Adjacent', 'block': 'repeat'}}, 'slot': 24}, {'item': {'id': 'bl_tag', 'data': {'option': 'False', 
    'tag': 'Include Origin Block', 'action': 'Adjacent', 'block': 'repeat'}}, 'slot': 25}, {'item': {'id': 'bl_tag', 'data': {'option': 'Adjacent (6 blocks)', 'tag': 'Pattern', 'action': 'Adjacent', 'block': 'repeat'}}, 'slot': 26}],
    'Path': [{'item': {'id': 'bl_tag', 'data': {'option': 'False', 'tag': 'Rotate Location', 'action': 'Path', 'block': 'repeat'}}, 'slot': 26}],
    'Sphere': [{'item': {'id': 'bl_tag', 'data': {'option': 'False', 'tag': 'Point Locations Inwards', 'action': 'Sphere', 'block': 'repeat'}}, 'slot': 26}],

}

#print(tagData['SendMessage'])