# Auto generated by pyre 2026-10-03T20:58:26.271520+00:00
from dfpyre.util.codeitem import CodeItem, add_slot


def _parse_color_value(color: tuple[int, int, int] | str):
    if isinstance(color, tuple):
        r, g, b = color
        hex_str = f'{r:02x}{g:02x}{b:02x}'
    else:
        hex_str = color.replace('#', 0).strip()
            
    return int(hex_str, base=16)


class Particle(CodeItem):
    """
    Represents a DiamondFire particle object.
    """
    type = 'part'
    
    def __init__(
            self, particle_name: str,
            amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, 
            size: float=None, size_variation: int=None,
            motion: tuple[float, float, float]=None, motion_variation: int=None,
            color: tuple[int, int, int] | str=None, color_variation: int=None,
            fade_color: tuple[int, int, int] | str=None,
            duration: int=None,
            opacity: int=None,
            roll: float=None,
            material: str=None,
            power: float=None,
            water_blocks: int=None, burst_impulse: float=None,
            slot: int | None=None
        ):
        super().__init__(slot)

        sub_data = {}

        if size is not None:
            sub_data['size'] = size
        
        if size_variation is not None:
            sub_data['sizeVariation'] = size_variation
        
        if motion is not None:
            sub_data['x'] = motion[0]
            sub_data['y'] = motion[1]
            sub_data['z'] = motion[2]
        
        if motion_variation is not None:
            sub_data['motionVariation'] = motion_variation
        
        if color is not None:
            sub_data['rgb'] = _parse_color_value(color)
        
        if color_variation is not None:
            sub_data['colorVariation'] = color_variation
        
        if fade_color is not None:
            sub_data['rgb_fade'] = _parse_color_value(fade_color)
        
        if duration is not None:
            sub_data['time'] = duration
        
        if opacity is not None:
            sub_data['opacity'] = opacity
        
        if roll is not None:
            sub_data['roll'] = roll
        
        if material is not None:
            sub_data['material'] = material

        if power is not None:
            sub_data['power'] = power

        if water_blocks is not None:
            sub_data['waterBlocks'] = water_blocks

        if burst_impulse is not None:
            sub_data['burstImpulse'] = burst_impulse
        
        self.particle_data = {
            'particle': particle_name,
            'cluster': {'amount': amount, 'horizontal': horizontal_spread, 'vertical': vertical_spread},
            'data': sub_data
        }
    
    @staticmethod
    def from_data(particle_data: dict, slot: int|None):
        p = Particle('temp', slot=slot)
        p.particle_data = particle_data
        return p
    
    def format(self, slot: int|None):
        formatted_dict = {"item": {"id": self.type, "data": self.particle_data}}
        add_slot(formatted_dict, self.slot or slot)
        return formatted_dict

    def __repr__(self) -> str:
        return f'{self.__class__.__name__}({self.particle_data})'

    @staticmethod
    def Rain(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Rain', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def Dolphin(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Dolphin', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def GlowingSquidGlow(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Glowing Squid Glow', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def Heart(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Heart', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def BubblePop(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Bubble Pop', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def DripstoneFallingWater(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Dripstone Falling Water', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def Flame(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Flame', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def GeyserBase(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0, water_blocks: int=2, burst_impulse: float=1.5):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        :param int water_blocks: The number of water blocks in the geyser water column.
        :param float burst_impulse: The force of the geyser burst.
        """
        return Particle('Geyser Base', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation, water_blocks=water_blocks, burst_impulse=burst_impulse)

    @staticmethod
    def SculkChargePop(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Sculk Charge Pop', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def Snowball(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Snowball', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def Nautilus(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Nautilus', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def Trail(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), color: tuple[int, int, int] | str=(255, 255, 255), color_variation: int=0, duration: int=5):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param tuple[int, int, int] | str color: The color of each particle.
        :param int color_variation: The percentage variation to apply to particle color.
        :param int duration: The duration of the effect in ticks.
        """
        return Particle('Trail', amount, horizontal_spread, vertical_spread, motion=motion, color=color, color_variation=color_variation, duration=duration)

    @staticmethod
    def RaidOmen(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Raid Omen', amount, horizontal_spread, vertical_spread, motion_variation=motion_variation)

    @staticmethod
    def TintedLeaves(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, color: tuple[int, int, int] | str=(255, 255, 255), color_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[int, int, int] | str color: The color of each particle.
        :param int color_variation: The percentage variation to apply to particle color.
        """
        return Particle('Tinted Leaves', amount, horizontal_spread, vertical_spread, color=color, color_variation=color_variation)

    @staticmethod
    def SporeBlossomAir(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Spore Blossom Air', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def FallingObsidianTear(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Falling Obsidian Tear', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def PaleOakLeaves(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Pale Oak Leaves', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def DrippingLava(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Dripping Lava', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def UpwardBubbleColumn(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Upward Bubble Column', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def Dust(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, color: tuple[int, int, int] | str=(255, 255, 255), color_variation: int=0, size: float=1.0, size_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[int, int, int] | str color: The color of each particle.
        :param int color_variation: The percentage variation to apply to particle color.
        :param float size: The size of each particle.
        :param int size_variation: The percentage variation to apply to particle size.
        """
        return Particle('Dust', amount, horizontal_spread, vertical_spread, color=color, color_variation=color_variation, size=size, size_variation=size_variation)

    @staticmethod
    def BlockMarker(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, material: str=None):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param str material: The block material to apply to each particle.
        """
        return Particle('Block Marker', amount, horizontal_spread, vertical_spread, material=material)

    @staticmethod
    def GustEmitterSmall(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Gust Emitter (Small)', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def HappyVillager(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Happy Villager', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def Enchant(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Enchant', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def WaxOn(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Wax On', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def CampfireSignalSmoke(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Campfire Signal Smoke', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def WaxOff(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Wax Off', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def SporeBlossomFall(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Spore Blossom Fall', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def SculkSoul(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Sculk Soul', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def Infested(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Infested', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def DamageIndicator(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Damage Indicator', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def Ash(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Ash', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def Explosion(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Explosion', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def Gust(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Gust', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def ElectricSpark(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Electric Spark', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def GustEmitterLarge(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Gust Emitter (Large)', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def FadeDust(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, color: tuple[int, int, int] | str=(255, 255, 255), fade_color: tuple[int, int, int] | str=(255, 255, 255), color_variation: int=0, size: float=1.0, size_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[int, int, int] | str color: The color of each particle.
        :param tuple[int, int, int] | str fade_color: The color that each particle will fade to.
        :param int color_variation: The percentage variation to apply to particle color.
        :param float size: The size of each particle.
        :param int size_variation: The percentage variation to apply to particle size.
        """
        return Particle('Fade Dust', amount, horizontal_spread, vertical_spread, color=color, fade_color=fade_color, color_variation=color_variation, size=size, size_variation=size_variation)

    @staticmethod
    def FallingDust(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, material: str=None):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param str material: The block material to apply to each particle.
        """
        return Particle('Falling Dust', amount, horizontal_spread, vertical_spread, material=material)

    @staticmethod
    def WhirlpoolBubbleColumn(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Whirlpool Bubble Column', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def DustPlume(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Dust Plume', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def Cobweb(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Cobweb', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def Lava(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Lava', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def ReversePortal(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Reverse Portal', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def TrialSpawnerDetection(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Trial Spawner Detection', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def Sneeze(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Sneeze', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def Bubble(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Bubble', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def LandingLava(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Landing Lava', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def DrippingWater(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Dripping Water', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def LandingHoney(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Landing Honey', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def Note(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, color: tuple[int, int, int] | str=(255, 255, 255), color_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[int, int, int] | str color: The color of each particle.
        :param int color_variation: The percentage variation to apply to particle color.
        """
        return Particle('Note', amount, horizontal_spread, vertical_spread, color=color, color_variation=color_variation)

    @staticmethod
    def Soul(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Soul', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def Mycelium(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Mycelium', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def Underwater(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Underwater', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def ExplosionEmitter(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Explosion Emitter', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def SmallGust(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Small Gust', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def Block(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, material: str=None):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param str material: The block material to apply to each particle.
        """
        return Particle('Block', amount, horizontal_spread, vertical_spread, material=material)

    @staticmethod
    def TotemofUndying(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Totem of Undying', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def LargeSmoke(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Large Smoke', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def OminousSpawning(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Ominous Spawning', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def GeyserPoof(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0, water_blocks: int=2, burst_impulse: float=1.5):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        :param int water_blocks: The number of water blocks in the geyser water column.
        :param float burst_impulse: The force of the geyser burst.
        """
        return Particle('Geyser Poof', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation, water_blocks=water_blocks, burst_impulse=burst_impulse)

    @staticmethod
    def Slime(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Slime', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def InstantEffect(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, power: float=1.0, color: tuple[int, int, int] | str=(255, 255, 255), color_variation: int=0, motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param float power: The power to apply to each particle.
        :param tuple[int, int, int] | str color: The color of each particle.
        :param int color_variation: The percentage variation to apply to particle color.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Instant Effect', amount, horizontal_spread, vertical_spread, power=power, color=color, color_variation=color_variation, motion_variation=motion_variation)

    @staticmethod
    def EntityEffect(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, color: tuple[int, int, int] | str=(255, 255, 255), opacity: int=100, color_variation: int=0, motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[int, int, int] | str color: The color of each particle.
        :param int opacity: The opacity of each particle.
        :param int color_variation: The percentage variation to apply to particle color.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Entity Effect', amount, horizontal_spread, vertical_spread, color=color, opacity=opacity, color_variation=color_variation, motion_variation=motion_variation)

    @staticmethod
    def FallingNectar(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Falling Nectar', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def CherryLeaves(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Cherry Leaves', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def Item(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, material: str=None, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param str material: The block material to apply to each particle.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Item', amount, horizontal_spread, vertical_spread, material=material, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def SculkCharge(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0, roll: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        :param float roll: The rotational roll of each particle in radians.
        """
        return Particle('Sculk Charge', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation, roll=roll)

    @staticmethod
    def ElderGuardian(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Elder Guardian', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def VaultConnection(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Vault Connection', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def Poof(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Poof', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def CopperFlame(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Copper Flame', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def ScrapeOxidization(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Scrape Oxidization', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def SonicBoom(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Sonic Boom', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def SweepAttack(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, size: float=1.0, size_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param float size: The size of each particle.
        :param int size_variation: The percentage variation to apply to particle size.
        """
        return Particle('Sweep Attack', amount, horizontal_spread, vertical_spread, size=size, size_variation=size_variation)

    @staticmethod
    def Shriek(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Shriek', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def Portal(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Portal', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def FallingLava(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Falling Lava', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def DragonBreath(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0, power: float=1.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        :param float power: The power to apply to each particle.
        """
        return Particle('Dragon Breath', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation, power=power)

    @staticmethod
    def SmallFlame(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Small Flame', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def EggCrack(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Egg Crack', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def AngryVillager(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Angry Villager', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def BlockCrumble(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, material: str=None):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param str material: The block material to apply to each particle.
        """
        return Particle('Block Crumble', amount, horizontal_spread, vertical_spread, material=material)

    @staticmethod
    def Splash(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Splash', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def CriticalHit(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Critical Hit', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def SoulFlame(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Soul Flame', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def Witch(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Witch', amount, horizontal_spread, vertical_spread, motion_variation=motion_variation)

    @staticmethod
    def GlowingSquidInk(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Glowing Squid Ink', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def Smoke(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Smoke', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def Spit(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Spit', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def FallingHoney(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Falling Honey', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def CampfireSmoke(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Campfire Smoke', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def Snowflake(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Snowflake', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def Flash(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, color: tuple[int, int, int] | str=(255, 255, 255), color_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[int, int, int] | str color: The color of each particle.
        :param int color_variation: The percentage variation to apply to particle color.
        """
        return Particle('Flash', amount, horizontal_spread, vertical_spread, color=color, color_variation=color_variation)

    @staticmethod
    def Fishing(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Fishing', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def Geyser(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, water_blocks: int=2):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param int water_blocks: The number of water blocks in the geyser water column.
        """
        return Particle('Geyser', amount, horizontal_spread, vertical_spread, water_blocks=water_blocks)

    @staticmethod
    def WhiteSmoke(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('White Smoke', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def SulfurCubeGoo(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Sulfur Cube Goo', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def SulfurBubbles(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Sulfur Bubbles', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def FallingWater(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Falling Water', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def SquidInk(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Squid Ink', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def DustPillar(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, material: str=None):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param str material: The block material to apply to each particle.
        """
        return Particle('Dust Pillar', amount, horizontal_spread, vertical_spread, material=material)

    @staticmethod
    def DrippingHoney(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Dripping Honey', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def EnchantedHit(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Enchanted Hit', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def WarpedSpore(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Warped Spore', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def DrippingObsidianTear(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Dripping Obsidian Tear', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def Cloud(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Cloud', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def EndRod(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('End Rod', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def Firefly(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Firefly', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def TrialOmen(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Trial Omen', amount, horizontal_spread, vertical_spread, motion_variation=motion_variation)

    @staticmethod
    def LandingObsidianTear(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Landing Obsidian Tear', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def Composter(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Composter', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def WhiteAsh(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('White Ash', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def CrimsonSpore(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Crimson Spore', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def DripstoneDrippingWater(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Dripstone Dripping Water', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def NoxiousGas(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Noxious Gas', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def Effect(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, power: float=1.0, color: tuple[int, int, int] | str=(255, 255, 255), color_variation: int=0, motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param float power: The power to apply to each particle.
        :param tuple[int, int, int] | str color: The color of each particle.
        :param int color_variation: The percentage variation to apply to particle color.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Effect', amount, horizontal_spread, vertical_spread, power=power, color=color, color_variation=color_variation, motion_variation=motion_variation)

    @staticmethod
    def TrialSpawnerDetectionOminous(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Trial Spawner Detection (Ominous)', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)

    @staticmethod
    def Vibration(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), duration: int=5):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int duration: The duration of the effect in ticks.
        """
        return Particle('Vibration', amount, horizontal_spread, vertical_spread, motion=motion, duration=duration)

    @staticmethod
    def NoxiousGasCloud(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Noxious Gas Cloud', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def DripstoneFallingLava(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Dripstone Falling Lava', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def DripstoneDrippingLava(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        """
        return Particle('Dripstone Dripping Lava', amount, horizontal_spread, vertical_spread)

    @staticmethod
    def GeyserPlume(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, water_blocks: int=2):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param int water_blocks: The number of water blocks in the geyser water column.
        """
        return Particle('Geyser Plume', amount, horizontal_spread, vertical_spread, water_blocks=water_blocks)

    @staticmethod
    def Firework(amount: int=1, horizontal_spread: float=0.0, vertical_spread: float=0.0, motion: tuple[float, float, float]=(0.0, 0.0, 0.0), motion_variation: int=0):
        """
        :param int amount: The number of particles to create.
        :param float horizontal_spread: The horizontal spread for the effect.
        :param float vertical_spread: The vertical spread for the effect.
        :param tuple[float, float, float] motion: The velocity to apply to the effect.
        :param int motion_variation: The percentage variation to apply to particle motion.
        """
        return Particle('Firework', amount, horizontal_spread, vertical_spread, motion=motion, motion_variation=motion_variation)
