"""
Generates `Literal` objects containing action names for each codeblock type.
This allows action names to be autocompleted if the user's IDE supports it.
"""

from datetime import datetime, timezone
from dfpyre.core.actiondump import ACTIONDUMP


OUTPUT_PATH = 'dfpyre/gen/action_literals.py'


def generate_action_literals():
    generated_lines: list[str] = [
        f'# Auto generated by pyre {datetime.now(timezone.utc).isoformat()}',
        'from typing import Literal\n'
    ]
    for codeblock_type, actions in ACTIONDUMP.action_data.items():
        if len(actions) == 1:
            continue

        filtered_actions = [a for a, d in actions.items() if not d.is_deprecated]  # Omit deprecated actions
        if not filtered_actions:
            continue
        action_list = str(filtered_actions)
        literal_line = f'{codeblock_type.upper()}_ACTION = Literal{action_list}'
        generated_lines.append(literal_line)
    
    game_value_names = list(ACTIONDUMP.game_values.keys())
    generated_lines += [
        f'GAME_VALUE_NAME = Literal{str(game_value_names)}',
        f'SOUND_NAME = Literal{str(ACTIONDUMP.sound_names)}',
        f'POTION_NAME = Literal{str(ACTIONDUMP.potion_names)}',
        'SUBACTION = IF_PLAYER_ACTION | IF_ENTITY_ACTION | IF_GAME_ACTION | IF_VAR_ACTION'
    ]
    
    with open(OUTPUT_PATH, 'w') as f:
        f.write('\n'.join(generated_lines) + '\n')


if __name__ == '__main__':
    generate_action_literals()
    print(f'Wrote codeblock action Literals to {OUTPUT_PATH}.')
