"""
Generates the `Particle` code item class.
"""

import re
from datetime import datetime, timezone
from dfpyre.core.actiondump import ACTIONDUMP, ParticleEntry
from dfpyre.gen.gen_data import INDENT
from dfpyre.gen.particle_gen_data import FIELD_PARAMETER_LOOKUP, CLASS_NAME, PARTICLE_CLASS_DEF, PARTICLE_METHOD_TEMPLATE


OUTPUT_PATH = 'dfpyre/export/particle_item.py'


def generate_particle_method(par_entry: ParticleEntry) -> str:
    method_name = re.sub(r'[^a-zA-Z0-9_]', '', par_entry.name)
    
    parameter_list: list[str] = []
    parameter_docstrings: list[str] = []
    argument_list: list[str] = []

    for field in par_entry.fields:
        field_param_data = FIELD_PARAMETER_LOOKUP[field]
        for param_data in field_param_data:
            param_name, param_type, param_default, param_description = param_data

            param_str = f'{param_name}: {param_type}={param_default}'
            parameter_list.append(param_str)

            param_docstr = f':param {param_type} {param_name}: {param_description}'
            parameter_docstrings.append(param_docstr)

            argument_str = f'{param_name}={param_name}'
            argument_list.append(argument_str)
    
    parameter_list_joined = ', ' + ', '.join(parameter_list) if parameter_list else ''
    docstr_delim = f'\n{INDENT*2}'
    docstrings_joined = docstr_delim + docstr_delim.join(parameter_docstrings) if parameter_docstrings else ''
    argument_list_joined = ', ' + ', '.join(argument_list) if argument_list else ''
    
    return PARTICLE_METHOD_TEMPLATE.format(
        method_name=method_name,
        parameter_list=parameter_list_joined,
        parameter_docstrings=docstrings_joined,
        class_name=CLASS_NAME,
        particle_name=par_entry.name,
        argument_list=argument_list_joined
    )


def generate_particle_class():
    generated_chunks: list[str] = [
        f'# Auto generated by pyre {datetime.now(timezone.utc).isoformat()}',
        PARTICLE_CLASS_DEF
    ]
    
    for par_entry in ACTIONDUMP.particle_data:
        method_lines = generate_particle_method(par_entry)
        generated_chunks.append(method_lines)

    with open(OUTPUT_PATH, 'w') as f:
        f.write('\n'.join(generated_chunks))


if __name__ == '__main__':
    generate_particle_class()
    print(f'Wrote Particle class to {OUTPUT_PATH}.')
